# Generated by Django 5.0.4 on 2024-04-22 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_times_alter_user_coins'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
