# Generated by Django 5.0.4 on 2024-04-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denounce', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='denounce',
            name='is_pass',
        ),
        migrations.AddField(
            model_name='denounce',
            name='denounce_status',
            field=models.PositiveIntegerField(choices=[(0, '待审核'), (1, '通过'), (2, '失败')], default=0),
        ),
    ]
