# Generated by Django 4.1.13 on 2024-08-08 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_alter_article_author_alter_article_content_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('denounce', '0002_remove_denounce_is_pass_denounce_denounce_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denounce',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.article', verbose_name='文章'),
        ),
        migrations.AlterField(
            model_name='denounce',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='denounce',
            name='denounce_status',
            field=models.PositiveIntegerField(choices=[(0, '待审核'), (1, '通过'), (2, '失败')], default=0, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='denounce',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='denounce',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='举报用户'),
        ),
    ]
