# Generated by Django 5.0.4 on 2024-04-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_article_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='expired',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
